Create recommendation database and table
Porters/matching-pro-recommendation-db pull request #1
Opened 2021-07-15 00:51 UTC by edwaltz89

SQL file for create DB and table

2021-07-16 01:46 UTC, SeraphicRav requested changes

2021-07-16 01:46 UTC, SeraphicRav commented on tables/1_createTable_recommendations.sql
> +    `summary` TEXT NULL COMMENT 'summary of job',
Why one is text and the over one is varchar ? Did you ask AI team about that ?

2021-07-16 01:46 UTC, SeraphicRav commented on tables/1_createTable_recommendations.sql
> +    `status` VARCHAR(255) NULL COMMENT 'recommendation status : scout | no-match',
I think the length of status can be shorter:
- scout has 5 letters
- no-match has 8 letters

Maybe 20 is enough in case we add other values

2021-07-16 01:46 UTC, SeraphicRav commented on tables/1_createTable_recommendations.sql
> +    `id` INTEGER NOT NULL AUTO_INCREMENT COMMENT 'Technical id',
Maybe a type bigger than integer should be used, we might have a lot of recommendations (number of resume x number of jobs)

2021-07-16 01:46 UTC, SeraphicRav commented on tables/1_createTable_recommendations.sql
> +    `source_id` INT NOT NULL COMMENT 'id of source table in mpro',
Please remove table from the comments, you can only say in MPRO instead

2021-07-20 07:08 UTC, edwaltz89 commented on tables/1_createTable_recommendations.sql
> +    `summary` TEXT NULL COMMENT 'summary of job',
I asked that wada san, and fixed to summary is VARCHAR(255) and JobDetail to TEXT

2021-07-20 07:08 UTC, edwaltz89 commented on tables/1_createTable_recommendations.sql
> +    `status` VARCHAR(255) NULL COMMENT 'recommendation status : scout | no-match',
fixed to VARCHAR(20)!

2021-07-20 07:08 UTC, edwaltz89 commented on tables/1_createTable_recommendations.sql
> +    `id` INTEGER NOT NULL AUTO_INCREMENT COMMENT 'Technical id',
fixed to BIGINT!

2021-07-20 07:09 UTC, edwaltz89 commented on tables/1_createTable_recommendations.sql
> +    `source_id` INT NOT NULL COMMENT 'id of source table in mpro',
fixed!

2021-07-26 00:26 UTC, SeraphicRav approved these changes

2021-07-27 00:06 UTC, merged